#!/usr/bin/env bash
# Copy to env.local.sh (ignored by Git) or export equivalent values before use.
# No GPU topology belongs here; hardware/runtime YAML owns role assignment.

_toolweave_env_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
export TOOLWEAVE_SOURCE_ROOT="${TOOLWEAVE_SOURCE_ROOT:-$(cd "$_toolweave_env_dir/.." && pwd -P)}"
export TOOLWEAVE_ROOT="$TOOLWEAVE_SOURCE_ROOT"
export TOOLWEAVE_ASSET_ROOT="${TOOLWEAVE_ASSET_ROOT:-$TOOLWEAVE_SOURCE_ROOT}"
export TOOLWEAVE_MODELS_ROOT="${TOOLWEAVE_MODELS_ROOT:-$TOOLWEAVE_ASSET_ROOT/models}"
export TOOLWEAVE_DATA_ROOT="${TOOLWEAVE_DATA_ROOT:-$TOOLWEAVE_ASSET_ROOT/stage1_format_rl/data}"
export TOOLWEAVE_SHARED_DATA_ROOT="${TOOLWEAVE_SHARED_DATA_ROOT:-$TOOLWEAVE_ASSET_ROOT/data}"
export TOOLWEAVE_ARTIFACTS_ROOT="${TOOLWEAVE_ARTIFACTS_ROOT:-$TOOLWEAVE_ASSET_ROOT/stage1_format_rl/artifacts}"
export TOOLWEAVE_OUTPUTS_ROOT="${TOOLWEAVE_OUTPUTS_ROOT:-$TOOLWEAVE_ASSET_ROOT/outputs}"
export TOOLWEAVE_LOGS_ROOT="${TOOLWEAVE_LOGS_ROOT:-$TOOLWEAVE_ASSET_ROOT/stage1_format_rl/logs}"
export TOOLWEAVE_REPORTS_ROOT="${TOOLWEAVE_REPORTS_ROOT:-$TOOLWEAVE_ASSET_ROOT/reports}"
export TOOLWEAVE_EVALS_ROOT="${TOOLWEAVE_EVALS_ROOT:-$TOOLWEAVE_ASSET_ROOT/evals}"
export TOOLWEAVE_CACHE_ROOT="${TOOLWEAVE_CACHE_ROOT:-$TOOLWEAVE_ASSET_ROOT/.cache}"
export TOOLWEAVE_TEMP_ROOT="${TOOLWEAVE_TEMP_ROOT:-$TOOLWEAVE_ASSET_ROOT/.runtime}"
export TOOLWEAVE_SHORT_TEMP_ROOT="${TOOLWEAVE_SHORT_TEMP_ROOT:-${TMPDIR:-/tmp}/toolweave}"
export TOOLWEAVE_PYTHON="${TOOLWEAVE_PYTHON:-$(command -v python)}"
export TOOLWEAVE_SYNTH_PYTHON="${TOOLWEAVE_SYNTH_PYTHON:-$TOOLWEAVE_PYTHON}"
export TOOLWEAVE_CONDA_ENV="${TOOLWEAVE_CONDA_ENV:-}"
export TOOLWEAVE_GENERATOR_ENDPOINT="${TOOLWEAVE_GENERATOR_ENDPOINT:-http://127.0.0.1:8000/v1}"
unset _toolweave_env_dir
